name: 'Deployment Tests'

on:
  push:
    branches:
      - master

jobs:
  unit-tests:
    name: 'Deployment tests'
    runs-on: ubuntu-latest
#    if: contains(github.head_ref, 'mcp') && (startswith(github.head_ref, 'feat/') || startswith(github.head_ref, 'bug/') || startswith(github.head_ref, 'patch/'))
    env:
      working-directory: ./tests/mcp/deployment
      GCP_PROJECT_ID: ${{secrets.GCP_PROJECT}}
#      GCP_PROJECT_ID: "mcpdeploytest-$(date '+%d%m%Y-%H%M')"

    defaults:
      run:
        shell: bash
        working-directory: ${{env.working-directory}}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{secrets.GCP_PROJECT}}
          service_account_key: ${{secrets.GCP_SA_KEY}}

      - name: Setup GCP
        run: |
          gcloud config set compute/zone europe-west2
          cd GCP/app/build/helloworld
          gcloud services enable cloudbuild.googleapis.com
          gcloud builds submit --tag gcr.io/${{secrets.GCP_PROJECT}}/helloworld
          cd ../../..
          echo 'name: ${{secrets.GCP_PROJECT}}-bucket' > project.yml
          echo 'project_id: $GCP_PROJECT_ID' | cat - gcp_ae.yml > temp && mv temp gcp_ae.yml
          echo 'image_uri: gcr.io/${GCP_PROJECT_ID}/helloworld' | cat - gcp_cloudrun.yml > temp && mv temp gcp_cloudrun.yml
          echo 'project_id: $GCP_PROJECT_ID' | cat - gcp_cloudrun.yml > temp && mv temp gcp_cloudrun.yml

      - name: Deploy GCP modules
        run: |
          cd GCP/terraform
          terraform init
          terraform plan
#          terraform apply -auto-approve

      - name: setup kubectl
        run: |
          gcloud components install kubectl
          gcloud container clusters create mcpdeploytest-cluster --num-nodes=1
          gcloud container clusters get-credentials mcpdeploytest-cluster

      - name: deploy k8s
        run: |
          cd ${env.working-directory}/k8s/terraform
          echo $PWD

      - name: error cleanup
        if: ${{ failure() }}
        run: echo "failed"


      #TODO: Deploy AWS